### ISSUE TITLE
Adapt to config.yaml changes

### ISSUE THREAD

**Issue by owtaylor** [Granite-Code/granite-code#61]
Originally, Continue had two layers of config merged together:

 1. `~/.continue/config.json`
 2. `<workspace>/.continuerc.json`

We add a third layer in our customization patches, so it is:

 1. Generated default config
 2. `~/.continue/config.json`
 3. `<workspace>/.continuerc.json`

However, with the 1.0 release of Continue, `config.json` is deprecated, and replaced by a new YAML configuration. In the YAML configuration, you can have multiple "assistants" (YAML config files), coming from different places:

* `~/.continue/config.yaml`
* `~/.continue/assistants/*.yaml` [since https://github.com/continuedev/continue/pull/4550]
* Assistants downloaded from `hub.continue.dev`

The idea is that if you want different behaviors (different docs sources, different precanned prompts) from different workspaces, then you should use a different assistant for each workspace. There is no longer any merging.

This obvously causes problems for our setup, but also seems less than ideal, because elements of the configuration (like your model configuration) will be duplicated in each workspace and have to be updated in each place. This is *partly* ameliorated for assistants on hub.continue.dev because there is a concept of "building blocks" (I think this is the name they use) where a YAML file can include snippets. But this doesn't apply locally to locally defined assistants, and even on the hub, there would still be a lot of duplication.

For example, the YAML file for a first assistant that I created looked like:

``` yaml
name: Owen's React Assistant
version: 0.0.2
schema: v1
models:
  - uses: anthropic/claude-3-7-sonnet
    with:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    override:
      roles:
        - chat
        - edit
  - uses: anthropic/claude-3-5-haiku
    with:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    override:
      roles:
        - apply
        - summarize
        - chat
  - uses: mistral/codestral
    with:
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
    override:
      roles:
        - autocomplete
  - uses: voyageai/rerank-2
    with:
      VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}
    override:
      roles:
        - rerank
  - uses: voyageai/voyage-code-3
    with:
      VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}
    override:
      roles:
        - embed
context:
  - uses: continuedev/code-context
  - uses: continuedev/docs-context
  - uses: continuedev/diff-context
  - uses: continuedev/terminal-context
  - uses: continuedev/problems-context
  - uses: continuedev/folder-context
  - uses: continuedev/codebase-context
docs:
  - uses: starter/react-docs
prompts:
  - uses: starter/test-prompt
rules:
  - uses: starter/react-rules

owtaylor/owens-react-assistant icon
```

A user would probably want all the stuff under `models` to be the same between different workspaces.

From what I've seen the design intent was to avoid dealing with the complexities of merging together different configurations. To adapt another assistant, you don't "include it", or "layer on top of it" (docker style), you "remix" it (scratch style).
